### ISSUE TITLE
问一下如何新建一个页面，并添加一个菜单

### ISSUE THREAD

**Issue by gejianya** [MannyCooper/anzifan.com#10]
问一下如何新建一个页面，并添加一个菜单，是不是还没这个功能？我看post里可以选择page，但是然而并没有什么用。

**Comment by MannyCooper** [comment]
是的，这个功能我在开发中。

**Comment by gejianya** [comment]
> 是的，这个功能我在开发中。
好的，感谢回复，期待中。
