### ISSUE TITLE
Deployment Details

### ISSUE THREAD

**Issue by leslieyin** [MannyCooper/anzifan.com#14]
部署的是dev版本，大佬帮忙看下这个咋回事

23:55:10	> Build error occurred
23:55:10	Error: Export encountered errors on following paths:
23:55:10		/
23:55:10		/about
23:55:10		/friends
23:55:10	    at /vercel/path0/node_modules/next/dist/export/index.js:408:19
23:55:10	    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
23:55:10	    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
23:55:10	    at async /vercel/path0/node_modules/next/dist/build/index.js:1342:21
23:55:10	    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by JIeJaitt** [comment]
同开发板：
```bash
ReferenceError: Worker is not defined
--
15:20:23.525 | at Object.<anonymous> (/vercel/path0/node_modules/@pixi/assets/lib/_virtual/checkImageBitmap.worker.js:22:30)
15:20:23.525 | at Module._compile (node:internal/modules/cjs/loader:1256:14)
15:20:23.525 | at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
15:20:23.525 | at Module.load (node:internal/modules/cjs/loader:1119:32)
15:20:23.525 | at Module._load (node:internal/modules/cjs/loader:960:12)
15:20:23.526 | at Module.require (node:internal/modules/cjs/loader:1143:19)
15:20:23.526 | at require (node:internal/modules/cjs/helpers:119:18)
15:20:23.526 | at Object.<anonymous> (/vercel/path0/node_modules/@pixi/assets/lib/loader/parsers/WorkerManager.js:2:31)
15:20:23.526 | at Module._compile (node:internal/modules/cjs/loader:1256:14)
15:20:23.526 | at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
15:20:23.528 |  
15:20:23.528 | > Build error occurred
15:20:23.530 | Error: Failed to collect page data for /about
15:20:23.530 | at /vercel/path0/node_modules/next/dist/build/utils.js:959:15 {
15:20:23.530 | type: 'Error'
15:20:23.531 | }
15:20:23.667 | error Command failed with exit code 1.
```

**Comment by JIeJaitt** [comment]
@leslieyin 你这个错误应该是没有切换新的notion模版，新模版在这儿：https://anzifan.notion.site/171707b7caa442afb7348b9231432f59?pvs=4

**Comment by leslieyin** [comment]
感谢哈，之前博主重新给我发过一次
